name: Bug Report
description: File a bug report
title: 'bug: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: '1.0.0'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, etc.
      placeholder: |
        Node: 24.x
        OS: Ubuntu 24.04
